FROM public.ecr.aws/pulumi/pulumi-python:latest

LABEL maintainer="Taylor Tobin <taylort@frm-ops.com>"

WORKDIR /hero-builder-api

COPY requirements.txt ./

COPY . .

RUN pip install --editable .

RUN pip install -r requirements.txt

CMD gunicorn --worker-class gevent --workers 4 --bind 0.0.0.0:5000 --keep-alive 2 "api:create_app()"
