FROM python:3.8.3-slim-buster

LABEL maintainer="Taylor Tobin <taylort@frm-ops.com>"

WORKDIR /hero-builder-api

COPY requirements.txt ./

COPY . .

RUN pip install -r requirements.txt

RUN pip install -e .

CMD ["flask", "run", "--host=0.0.0.0"]
